#!/usr/bin/env bash
# my subdomains information
# www --> 35.175.135.18
# web-01 --> 54.89.21.208
# web-02 --> 35.153.194.6
display_info ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
	display_info "$1" "$subdomain"
    fi
done
