#!/usr/bin/env bash
#this bash script displays to infinity and beyond.
#iterates in a while loop to infinity
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
